### ISSUE TITLE
on_alarm and on_alarm_restored zone type?

### ISSUE THREAD

**Issue by TD22057** [nutechsoftware/alarmdecoder#10]
The callback on_zone_fault passes the zone as an integer.  The callbacks on_alarm and on_alarm_restored pass the zone as a string.  Should these be consistent?  It seems like the alarm callbacks should be changed to pass the zone as an integer.

**Comment by endlesscoil** [comment]
Yup, agreed that those should be consistent.  It looks like I already took care of this in one of the branches I'm working on, so it should be fixed up come next release.
