### ISSUE TITLE
is the API stable?

### ISSUE THREAD

**Issue by jmgurney** [nutechsoftware/alarmdecoder#13]
I see that the latest release is major version 0.  Per http://semver.org/#spec-item-4 :
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So, this means that anyone developing against the library will have to fix their code against a specific version or commit, and not automatically get any bug fixes that may be release, or they risk the new version of code breaking their library.

Could you please release major version 1 so that developers can depend upon a stable API?

Thanks.

**Comment by endlesscoil** [comment]
Yup, I agree.  The API has been stable for quite a while now.  The current revision is now 1.13.0.  Thanks for the suggestion.
