### ISSUE TITLE
Please upload 0.13.1 to pypi

### ISSUE THREAD

**Issue by PhracturedBlue** [nutechsoftware/alarmdecoder#18]
Please upload 0.13.1 to pypi so we can include the updates in homeassistant

**Comment by billimek** [comment]
FYI 0.13.1 doesn't include #17

**Comment by PhracturedBlue** [comment]
Oops.  Didn't realize that.  can we get the fix from #17 into 0.13.2 and get that on pypi then?

**Comment by f34rdotcom** [comment]
Updated to 1.13.2 to pypi please tests.

**Comment by PhracturedBlue** [comment]
Just an FYI, that I'm having some issues with this release.  On loss of connection, I am not able to restart the connection anymore.  I haven't debugged it yet, so I don't know if the issue is on the home-assistant end or  the alarmdecoder side.  I'll update once I have more information.

**Comment by PhracturedBlue** [comment]
Sorry for the false alarm.  The issue was on my end.  1.13.2 is working fine in alarm-decoder for me now.
