### ISSUE TITLE
Build 1.13.5 and publish to pypi

### ISSUE THREAD

**Issue by jonathanjsimon** [nutechsoftware/alarmdecoder#33]
This is almost entirely self serving. I have some pull requests in at homeassistant that depend on the pull requests I submitted here. They were merged but no new version was published.

Thanks!

**Comment by f34rdotcom** [comment]
Thanks! Fixed b0c014089e24455228cb4402cf30ba98157578cd

**Comment by jonathanjsimon** [comment]
Did this get published as 1.13.5 to pypi? I'm still seeing 1.13.4 as the latest version on https://pypi.org/project/alarmdecoder/. Thanks!

**Comment by f34rdotcom** [comment]
Ya I messed up. I did not notice it was on master this needed to be done on dev. I am working on 1.13.6 in dev currently and when I merge that all over then I will update pypi. I had planned on shipping this on Monday but I found things I did not like so I am still working on a good well tested stable release in the next 2 days.

**Comment by jonathanjsimon** [comment]
Ah! I also messed up because I pushed to my fork of `dev` but never created a PR for it to get merged into yours. Sorry!

**Comment by jonathanjsimon** [comment]
> Ah! I also messed up because I pushed to my fork of `dev` but never created a PR for it to get merged into yours. Sorry!

Or rather.....I second guessed myself. Nevermind on this comment.
