### ISSUE TITLE
Feature Request: Add armed instant status

### ISSUE THREAD

**Issue by HeySideburns** [nutechsoftware/alarmdecoder#34]
I would love to be able to check if my alarm is in instant mode and change my smartthings behavior accordingly. I have pets so I never arm my alarm in away mode unless we are on vacation and have the pets boarded. If we are leaving the house, we arm stay, before we go to bed for the night we arm instant. I'd like to differentiate between those so I can do something like the following. 

If the alarm is armed_stay, turn on interior and exterior security cameras. If the alarm is armed_instant, only turn on the external security cameras.

**Comment by f34rdotcom** [comment]
status bits relevant to alarm status that are missing in the rest api.
entry_delay_off
perimeter_only
alarm_event_occurred

**Comment by f34rdotcom** [comment]
Ok added  panel_perimeter_only, panel_entry_delay_off and virtual devices in smartthings project. Still in dev bout out soon.

**Comment by HeySideburns** [comment]
Great, thanks!
