### ISSUE TITLE
pyserial requirements.txt breaks homeassistant

### ISSUE THREAD

**Issue by garbled1** [nutechsoftware/alarmdecoder#43]
The highest version of alarmdecoder published on pypi is 1.13.6, but the commit that fixed requirements.txt to allow pyserial>=2.7 instead of pyserial==2.7 was made after that release.

Hard setting pyserial to 2.7 breaks insteonplm in homeassistant.  Please ship a new version to pypi with the requirements.txt patch.

**Comment by f34rdotcom** [comment]
Done. I added a release for 1.13.8 and pushed it to pypy.

**Comment by garbled1** [comment]
alarmdecoder 1.13.8 has requirement pyserial==2.7, but you'll have pyserial 3.2 which is incompatible.

Did the requirements not get updated?

**Comment by f34rdotcom** [comment]
I thought they were :( . I will check again tomorrow night when I get back.

**Comment by garbled1** [comment]
Oh, I think the problem is not requirements.txt, but the requirements section of setup.py.  Apparently that is what triggers pip.  My bad.  :(

**Comment by f34rdotcom** [comment]
Nice find. I need to learn more about setup and how it relates to requirements. Seems this is duplicate data and will lead to issues again. For now it is fixed and I am going to build and publish to pypy shortly. Thanks for finding that.

**Comment by garbled1** [comment]
Np, I'm just kinda figuring it out myself on a library I've been writing the past week.  I think the idea is this:

requirements.txt is for manual building.  So you just do pip install -r requirements.txt
setup.py is what pypy uses.
