### ISSUE TITLE
Expander Zones Are Reported in Messages

### ISSUE THREAD

**Issue by krkeegan** [nutechsoftware/alarmdecoder#51]
zonetracking.py contains this note:

```
                # NOTE: Expander zone faults are handled differently than
                #       regular messages.  We don't include them in
                #       self._zones_faulted because they are not reported
                #       by the panel in it's rolling list of faults.
```

At least on my panel (Vista 20SE) the expander zones are still reported in the rolling messages.  They are also reported as ready or faulted using the !EXP messages.  Because they appear in the rolling message list, _clear_zones ends up placing them in the _zones_faulted array anyways.

The only concern this causes, is that any error in _clear_zones such as #50 will affect expander zones when it doesn't need to.

**Comment by f34rdotcom** [comment]
Will merge into dev once I sort this serial issue out. I expect it wont take long for some feedback on the serial patch.
