### ISSUE TITLE
"Events" log (zone events) log with UTC timestamps despite setting timezone

### ISSUE THREAD

**Issue by melikyuksel** [nutechsoftware/alarmdecoder#6]
The other two logs (Live and App) log in the local timezone as expected, but the Events log (the one that displays zone faults and restores, fire alarms, etc.) on the web app seems to always log in UTC time regardless of the local timezone set with `dpkg-reconfigure tzdata` and displayed with `timedatctl` or `date`.

**Comment by weevis** [comment]
In the most recent update there was a change in the dataTables API after a plugin upgrade - this is fixed locally and will be pushed up in the next release.
