### ISSUE TITLE
The new responsive design seems to miscalculate mobile screen width

### ISSUE THREAD

**Issue by melikyuksel** [nutechsoftware/alarmdecoder#7]
On iOS, the latest webapp design seems to think the iPhone screen is a lot wider than it really is, hence making all the text really small. Among the resulting issues, the keypad buttons end up really tiny and almost impossible to press.

**Comment by weevis** [comment]
Please provide screenshot

**Comment by melikyuksel** [comment]
![img_0946](https://cloud.githubusercontent.com/assets/10296053/22501841/8502da8a-e838-11e6-9d40-6ab4c43e4427.PNG)

**Comment by endlesscoil** [comment]
This should be fixed in the release that was pushed up today.  

In the future please open issues relating to the webapp over on the webapp repository:
https://github.com/nutechsoftware/alarmdecoder-webapp

Thanks!
